# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np)

<module 'numpy' from 'C:\\Users\\Administrateur\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


In [4]:
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.0102083  0.80816543 0.79000409 0.38996835 0.60218509]
  [0.79191596 0.74390411 0.7363601  0.59685676 0.95208619]
  [0.08253545 0.368198   0.00899738 0.29978063 0.63835041]]

 [[0.00417069 0.5590494  0.2344424  0.74710626 0.69740295]
  [0.20513303 0.23275626 0.23909537 0.26669844 0.4243566 ]
  [0.46531752 0.44358768 0.63187235 0.0582095  0.69081154]]]


In [29]:
# Method 2
a = np.random.randint(10, size=(2,3,5))
print(a)


[[[0 1 4 8 8]
  [0 5 1 4 6]
  [3 8 2 5 8]]

 [[1 7 5 5 5]
  [0 7 2 0 1]
  [5 8 9 0 0]]]


In [50]:
# Method 3
a=np.random.sample((2,3,5))
print(a)

[[[0.03507566 0.09884014 0.36563973 0.47165694 0.77133472]
  [0.48440166 0.0114853  0.96221486 0.89218203 0.90410999]
  [0.02321119 0.6024549  0.79396908 0.13675246 0.89071912]]

 [[0.86904136 0.86084534 0.97813662 0.6499642  0.98092484]
  [0.66844469 0.32051761 0.99658808 0.31979064 0.15835349]
  [0.96743299 0.73561697 0.06927777 0.77407802 0.92472797]]]


#### 4. Print *a*.


In [9]:
print(a)

[[[0.0102083  0.80816543 0.79000409 0.38996835 0.60218509]
  [0.79191596 0.74390411 0.7363601  0.59685676 0.95208619]
  [0.08253545 0.368198   0.00899738 0.29978063 0.63835041]]

 [[0.00417069 0.5590494  0.2344424  0.74710626 0.69740295]
  [0.20513303 0.23275626 0.23909537 0.26669844 0.4243566 ]
  [0.46531752 0.44358768 0.63187235 0.0582095  0.69081154]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
b=np.ones((5,2,3))

In [13]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
b=np.array([[[1, 1, 1], [1,1,1]], [[1, 1, 1], [1,1,1]], [[1, 1, 1], [1,1,1]], [[1, 1, 1], [1,1,1]], [[1, 1, 1], [1,1,1]]])
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 6. Print *b*.


In [12]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
print(a.shape)

(2, 3, 5)


In [17]:
print(b.shape)

(5, 2, 3)


In [18]:
a.shape==b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [46]:
c= np.transpose(b, axes=(1, 2,0))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [47]:
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [52]:
d=c+a
d

array([[[1.03507566, 1.09884014, 1.36563973, 1.47165694, 1.77133472],
        [1.48440166, 1.0114853 , 1.96221486, 1.89218203, 1.90410999],
        [1.02321119, 1.6024549 , 1.79396908, 1.13675246, 1.89071912]],

       [[1.86904136, 1.86084534, 1.97813662, 1.6499642 , 1.98092484],
        [1.66844469, 1.32051761, 1.99658808, 1.31979064, 1.15835349],
        [1.96743299, 1.73561697, 1.06927777, 1.77407802, 1.92472797]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [54]:
print(a)
print(d)
print(d-a)

[[[0.03507566 0.09884014 0.36563973 0.47165694 0.77133472]
  [0.48440166 0.0114853  0.96221486 0.89218203 0.90410999]
  [0.02321119 0.6024549  0.79396908 0.13675246 0.89071912]]

 [[0.86904136 0.86084534 0.97813662 0.6499642  0.98092484]
  [0.66844469 0.32051761 0.99658808 0.31979064 0.15835349]
  [0.96743299 0.73561697 0.06927777 0.77407802 0.92472797]]]
[[[1.03507566 1.09884014 1.36563973 1.47165694 1.77133472]
  [1.48440166 1.0114853  1.96221486 1.89218203 1.90410999]
  [1.02321119 1.6024549  1.79396908 1.13675246 1.89071912]]

 [[1.86904136 1.86084534 1.97813662 1.6499642  1.98092484]
  [1.66844469 1.32051761 1.99658808 1.31979064 1.15835349]
  [1.96743299 1.73561697 1.06927777 1.77407802 1.92472797]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [55]:
e=a*c
e

array([[[0.03507566, 0.09884014, 0.36563973, 0.47165694, 0.77133472],
        [0.48440166, 0.0114853 , 0.96221486, 0.89218203, 0.90410999],
        [0.02321119, 0.6024549 , 0.79396908, 0.13675246, 0.89071912]],

       [[0.86904136, 0.86084534, 0.97813662, 0.6499642 , 0.98092484],
        [0.66844469, 0.32051761, 0.99658808, 0.31979064, 0.15835349],
        [0.96743299, 0.73561697, 0.06927777, 0.77407802, 0.92472797]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [56]:
print(c)
# e equals a cause c is an array with all elements equal to 1

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
d_max=d.max()
d_max

1.9965880761709793

In [60]:
d_min=d.min()
d_min

1.011485302861927

In [61]:
d_mean=d.mean()
d_mean

1.5905929460038002

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [66]:
f=np.empty((2,3,5))
f

array([[[0.03507566, 0.09884014, 0.36563973, 0.47165694, 0.77133472],
        [0.48440166, 0.0114853 , 0.96221486, 0.89218203, 0.90410999],
        [0.02321119, 0.6024549 , 0.79396908, 0.13675246, 0.89071912]],

       [[0.86904136, 0.86084534, 0.97813662, 0.6499642 , 0.98092484],
        [0.66844469, 0.32051761, 0.99658808, 0.31979064, 0.15835349],
        [0.96743299, 0.73561697, 0.06927777, 0.77407802, 0.92472797]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [70]:
print(d)

[[[1.03507566 1.09884014 1.36563973 1.47165694 1.77133472]
  [1.48440166 1.0114853  1.96221486 1.89218203 1.90410999]
  [1.02321119 1.6024549  1.79396908 1.13675246 1.89071912]]

 [[1.86904136 1.86084534 1.97813662 1.6499642  1.98092484]
  [1.66844469 1.32051761 1.99658808 1.31979064 1.15835349]
  [1.96743299 1.73561697 1.06927777 1.77407802 1.92472797]]]


In [69]:
for i, value_i in enumerate(d):
    for j, value_j in enumerate(value_i):
        for index, value in enumerate(value_j):
            if value > d_min and value < d_mean:
                value = 25
                f[i][j][index] = value
        
            if value > d_mean and value < d_max:
                value = 75
                f[i][j][index] = value
        
            if value == d_mean:
                value = 50
                f[i][j][index] = value
        
            if value == d_min:
                value = 0
                f[i][j][index] = value
        
            if value == d_max:
                value = 100
                f[i][j][index] = value
                
print(f)

[[[ 25.  25.  25.  25.  75.]
  [ 25.   0.  75.  75.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  25. 100.  25.  25.]
  [ 75.  75.  25.  75.  75.]]]


In [75]:
f =[]
for x in np.nditer(d):
    if x > d_min and x < d_mean:
            f  += [25]
    elif x > d_mean and x < d_max:
            f  += [75]
    elif x == d_mean:
            f  += [50]
    elif x == d_min:
            f  += [0]
    elif x == d_max:
            f  += [100]
f = np.reshape(f, d.shape)
f

array([[[ 25,  25,  25,  25,  75],
        [ 25,   0,  75,  75,  75],
        [ 25,  75,  75,  25,  75]],

       [[ 75,  75,  75,  75,  75],
        [ 75,  25, 100,  25,  25],
        [ 75,  75,  25,  75,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [71]:
print(d)
print(f)

[[[1.03507566 1.09884014 1.36563973 1.47165694 1.77133472]
  [1.48440166 1.0114853  1.96221486 1.89218203 1.90410999]
  [1.02321119 1.6024549  1.79396908 1.13675246 1.89071912]]

 [[1.86904136 1.86084534 1.97813662 1.6499642  1.98092484]
  [1.66844469 1.32051761 1.99658808 1.31979064 1.15835349]
  [1.96743299 1.73561697 1.06927777 1.77407802 1.92472797]]]
[[[ 25.  25.  25.  25.  75.]
  [ 25.   0.  75.  75.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  25. 100.  25.  25.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [74]:
f =[]
for x in np.nditer(d):
    if x > d_min and x < d_mean:
            f  += ['D']
    elif x > d_mean and x < d_max:
            f  += ['B']
    elif x == d_mean:
            f  += ['C']
    elif x == d_min:
            f  += ['E']
    elif x == d_max:
            f  += ['A']
f = np.reshape(f, d.shape)
f

array([[['D', 'D', 'D', 'D', 'B'],
        ['D', 'E', 'B', 'B', 'B'],
        ['D', 'B', 'B', 'D', 'B']],

       [['B', 'B', 'B', 'B', 'B'],
        ['B', 'D', 'A', 'D', 'D'],
        ['B', 'B', 'D', 'B', 'B']]], dtype='<U1')